### ISSUE TITLE
Recommended hardware requirements

### ISSUE THREAD

**Issue by slambrechts** [WatsonLab/MAGpy#10]
Hi there,

MAGpy seems like an interesting tool I would like to use, but I was wondering if you could add any information regarding system requirements? I understand resource requirements for this pipeline will vary greatly based on the amount of data being processed, but can you recommend a minimum and ideal amount of cores, RAM and storage space to succesfully run MAGpy on (for example) 100 MAGs?

Best regards,

Sam

**Comment by mw55309** [comment]
If you look in MAGpy.json it should suggest a few of the resource requirements needed for each task
