### ISSUE TITLE
The incompatible packages with each other

### ISSUE THREAD

**Issue by SarahIsme** [WatsonLab/MAGpy#17]
Hello,

I installed MAGpy as the 10-min-installation, and at the last step, it showed:

> Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package libgfortran-ng conflicts for:
scipy -> libgfortran-ng[version='>=7,<8.0a0|>=7.2.0,<8.0a0']
Package python conflicts for:
mercurial=4.5 -> python[version='2.7.*|>=2.7,<2.8.0a0']
scipy -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
graphlan=1.0.0 -> python=2.7
Package libgcc conflicts for:
fasttree=2.1.10 -> libgcc
muscle=3.8.1551 -> libgcc
scipy -> libgcc
Package libgcc-ng conflicts for:
muscle=3.8.1551 -> libgcc-ng[version='>=7.3.0']
fasttree=2.1.10 -> libgcc-ng[version='>=4.9|>=7.3.0']
scipy -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
python=2.7 -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
mercurial=4.5 -> libgcc-ng[version='>=7.2.0']
Package liblapack conflicts for:
scipy -> liblapack[version='>=3.8.0,<3.9.0a0']
Package biopython conflicts for:
graphlan=1.0.0 -> biopython=1.66
Package libstdcxx-ng conflicts for:
muscle=3.8.1551 -> libstdcxx-ng[version='>=4.9|>=7.3.0']
scipy -> libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.3.0']
python=2.7 -> libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.3.0']
Package * conflicts for:
scipy -> *[track_features=blas_openblas]
Package pip conflicts for:
python=2.7 -> pip
Package mkl conflicts for:
scipy -> mkl[version='>=2018.0.0,<2019.0a0|>=2018.0.2,<2019.0a0|>=2018.0.3,<2019.0a0|>=2019.1,<2020.0a0|>=2019.4,<2020.0a0']
Package libffi conflicts for:
python=2.7 -> libffi[version='3.2.*|>=3.2.1,<3.3.0a0|>=3.2.1,<4.0a0']
Package sqlite conflicts for:
python=2.7 -> sqlite[version='3.13.*|3.20.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0']
Package readline conflicts for:
python=2.7 -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
Package mkl-service conflicts for:
scipy -> mkl-service[version='>=2,<3.0a0']
Package openssl conflicts for:
python=2.7 -> openssl[version='1.0.*|1.0.*,>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a']
Package numpy conflicts for:
scipy -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11|>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.15.1,<2.0a0|>=1.9|>=1.9.3,<2.0a0']
Package ncurses conflicts for:
python=2.7 -> ncurses[version='5.9.*|6.0.*|>=6.0,<7.0a0|>=6.1,<6.2.0a0|>=6.1,<7.0a0']
Package tk conflicts for:
python=2.7 -> tk[version='8.5.*|8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
Package matplotlib conflicts for:
graphlan=1.0.0 -> matplotlib[version='1.4.*|1.5.*']
Package zlib conflicts for:
python=2.7 -> zlib[version='1.2.*|1.2.11.*|1.2.11|1.2.8|>=1.2.11,<1.3.0a0']
Package ca-certificates conflicts for:
python=2.7 -> ca-certificates
Package bzip2 conflicts for:
python=2.7 -> bzip2[version='>=1.0.6,<2.0a0']
Package libgfortran conflicts for:
scipy -> libgfortran[version='>=3.0']
Package libcblas conflicts for:
scipy -> libcblas[version='>=3.8.0,<4.0a0']
Package libblas conflicts for:
scipy -> libblas[version='>=3.8.0,<4.0a0']
Package libopenblas conflicts for:
scipy -> libopenblas[version='>=0.2.20,<0.2.21.0a0|>=0.3.2,<0.3.3.0a0|>=0.3.3,<1.0a0']
Package blas conflicts for:
scipy -> blas[version='*|*|1.0|1.1',build='openblas|openblas|openblas|mkl|mkl']
Package openblas conflicts for:
scipy -> openblas[version='0.2.18.*|0.2.18|0.2.18.*|0.2.19|0.2.19.*|0.2.20|0.2.20.*|>=0.2.20,<0.2.21.0a0|>=0.3.3,<0.3.4.0a0']
Package pygments conflicts for:
mercurial=4.5 -> pygments

Could you please tell me how to solve the problems?

Best regards,

Sarah

**Comment by shashankx** [comment]
Also getting a similar error in the last step-

```
conda env create -f MAGpy/envs/basic2.yaml
Collecting package metadata (repodata.json): done
Solving environment: failed
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package sqlite conflicts for:
python=2.7 -> sqlite[version='3.13.*|3.20.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0']
Package mkl-service conflicts for:
scipy -> mkl-service[version='>=2,<3.0a0']
Package libgcc-ng conflicts for:
fasttree=2.1.10 -> libgcc-ng[version='>=4.9|>=7.3.0']
mercurial=4.5 -> libgcc-ng[version='>=7.2.0']
python=2.7 -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
muscle=3.8.1551 -> libgcc-ng[version='>=7.3.0']
scipy -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
Package libstdcxx-ng conflicts for:
python=2.7 -> libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.3.0']
muscle=3.8.1551 -> libstdcxx-ng[version='>=4.9|>=7.3.0']
scipy -> libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.3.0']
Package libgcc conflicts for:
muscle=3.8.1551 -> libgcc
scipy -> libgcc
fasttree=2.1.10 -> libgcc
Package mkl conflicts for:
scipy -> mkl[version='>=2018.0.0,<2019.0a0|>=2018.0.2,<2019.0a0|>=2018.0.3,<2019.0a0|>=2019.1,<2020.0a0|>=2019.4,<2020.0a0']
Package matplotlib conflicts for:
graphlan=1.0.0 -> matplotlib[version='1.4.*|1.5.*']
Package libgfortran-ng conflicts for:
scipy -> libgfortran-ng[version='>=7,<8.0a0|>=7.2.0,<8.0a0']
Package ncurses conflicts for:
python=2.7 -> ncurses[version='5.9.*|6.0.*|>=6.0,<7.0a0|>=6.1,<6.2.0a0|>=6.1,<7.0a0']
Package ca-certificates conflicts for:
python=2.7 -> ca-certificates
Package python conflicts for:
mercurial=4.5 -> python[version='2.7.*|>=2.7,<2.8.0a0']
graphlan=1.0.0 -> python=2.7
scipy -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
Package libffi conflicts for:
python=2.7 -> libffi[version='3.2.*|>=3.2.1,<3.3.0a0|>=3.2.1,<4.0a0']
Package openblas conflicts for:
scipy -> openblas[version='0.2.18.*|0.2.18|0.2.18.*|0.2.19|0.2.19.*|0.2.20|0.2.20.*|>=0.2.20,<0.2.21.0a0|>=0.3.3,<0.3.4.0a0']
Package * conflicts for:
scipy -> *[track_features=blas_openblas]
Package bzip2 conflicts for:
python=2.7 -> bzip2[version='>=1.0.6,<2.0a0']
Package readline conflicts for:
python=2.7 -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
Package libcblas conflicts for:
scipy -> libcblas[version='>=3.8.0,<4.0a0']
Package libgfortran conflicts for:
scipy -> libgfortran[version='>=3.0']
Package zlib conflicts for:
python=2.7 -> zlib[version='1.2.*|1.2.11.*|1.2.11|1.2.8|>=1.2.11,<1.3.0a0']
Package biopython conflicts for:
graphlan=1.0.0 -> biopython=1.66
Package pip conflicts for:
python=2.7 -> pip
Package libblas conflicts for:
scipy -> libblas[version='>=3.8.0,<4.0a0']
Package pygments conflicts for:
mercurial=4.5 -> pygments
Package tk conflicts for:
python=2.7 -> tk[version='8.5.*|8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
Package openssl conflicts for:
python=2.7 -> openssl[version='1.0.*|1.0.*,>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a']
Package liblapack conflicts for:
scipy -> liblapack[version='>=3.8.0,<3.9.0a0']
Package blas conflicts for:
scipy -> blas[version='*|*|1.0|1.1',build='mkl|mkl|openblas|openblas|openblas']
Package libopenblas conflicts for:
scipy -> libopenblas[version='>=0.2.20,<0.2.21.0a0|>=0.3.2,<0.3.3.0a0|>=0.3.3,<1.0a0']
Package numpy conflicts for:
scipy -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11|>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.15.1,<2.0a0|>=1.9|>=1.9.3,<2.0a0']

```

Any suggestions?

**Comment by mw55309** [comment]
Hi

I have updated a couple of the environments, hopefully this should help 

Let me know

Mick

**Comment by shashankx** [comment]
Hi Mick,
So, should I install the MAGpy again from the beginning?
Best,
Shashank

**Comment by shashankx** [comment]
Hi Mick,
Now the installation was successful, but now got the error while running on the test data-
```
(magpy_install) [s176365@computerome01 MAGpy]$ snakemake --use-conda -s MAGpy --cores 26
Building DAG of jobs...
Creating conda environment envs/ete3.yaml...
Downloading remote packages.
Environment for envs/ete3.yaml created (location: .snakemake/conda/dea548e9)
Creating conda environment envs/diamond.yaml...
Downloading remote packages.
Environment for envs/diamond.yaml created (location: .snakemake/conda/23fdcf8e)
Using shell: /bin/bash
Provided cores: 26
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       checkm
        1       checkm_plus
        1       diamond
        1       diamond_bin_summary
        1       diamond_bin_summary_plus
        1       diamond_report
        1       pfam_scan
        1       phylophlan_link
        1       prodigal
        1       sourmash_gather
        1       sourmash_report
        1       sourmash_sig
        13

[Fri Dec 20 11:41:18 2019]
rule prodigal:
    input: mags/ecoli.fa
    output: proteins/ecoli.faa, proteins/ecoli_prodigal.gff
    jobid: 9
    wildcards: id=ecoli

Activating conda environment: /home/projects/cu_10108/data/Raw/Shashank/GrowthDynamics_Project/MAGpy/.snakemake/conda/ec91b048

[Fri Dec 20 11:41:18 2019]
rule sourmash_sig:
    input: mags/ecoli.fa
    output: sourmash/ecoli.sig
    jobid: 11
    wildcards: id=ecoli

Activating conda environment: /home/projects/cu_10108/data/Raw/Shashank/GrowthDynamics_Project/MAGpy/.snakemake/conda/c2437986
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
/bin/bash: sourmash: command not found
[Fri Dec 20 11:41:19 2019]
Error in rule sourmash_sig:
    jobid: 11
    output: sourmash/ecoli.sig
    conda-env: /home/projects/cu_10108/data/Raw/Shashank/GrowthDynamics_Project/MAGpy/.snakemake/conda/c2437986

RuleException:
CalledProcessError in line 83 of /home/projects/cu_10108/data/Raw/Shashank/GrowthDynamics_Project/MAGpy/MAGpy:
Command 'source activate /home/projects/cu_10108/data/Raw/Shashank/GrowthDynamics_Project/MAGpy/.snakemake/conda/c2437986; source $HOME/.bashrc;  sourmash compute --scaled 1000 -k 31 -o sourmash/ecoli.sig mags/ecoli.fa ' returned non-zero exit status 127.
  File "/home/projects/cu_10108/data/Raw/Shashank/GrowthDynamics_Project/MAGpy/MAGpy", line 83, in __rule_sourmash_sig
  File "/home/people/s176365/miniconda3/envs/magpy_install/lib/python3.6/concurrent/futures/thread.py", line 56, in run
[Fri Dec 20 11:42:21 2019]
Finished job 9.
1 of 13 steps (8%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/projects/cu_10108/data/Raw/Shashank/GrowthDynamics_Project/MAGpy/.snakemake/log/2019-12-20T111237.898689.snakemake.log
```

**Comment by susheelbhanu** [comment]
@shashankx this problem usually comes from conda not having the correct permissions. Did you run ```chmod -R 755``` on the original folder, i.e. ```chmod -R 755 MAGpy```

Mine was resolved with this; hope it's the case for you as well. :)
