### ISSUE TITLE
error while running pfam

### ISSUE THREAD

**Issue by shashankx** [WatsonLab/MAGpy#19]
Hi, 
I got en error while running the MAGpy on mags.

**[Mon Nov 18 12:52:21 2019]
Finished job 109.
173 of 373 steps (46%) done
Activating conda environment: /mibi/users/jsb562/MAGpy/.snakemake/conda/b0d3265a
FATAL: can't find "active_site.dat" in "/mibi/users/jsb562/MAGpy/pfam" at /mibi/users/jsb562/MAGpy/.snakemake/conda/b0d3265a/share/pfam_scan-1.6-3/pfam_scan.pl line 92.
[Mon Nov 18 12:52:25 2019]
Error in rule pfam_scan:
    jobid: 36
    output: pfam/18097D-02-03_bin.6.pfam
    conda-env: /mibi/users/jsb562/MAGpy/.snakemake/conda/b0d3265a
    shell:
        pfam_scan.pl -outfile pfam/18097D-02-03_bin.6.pfam -as -cpu 8 -fasta proteins/18097D-02-03_bin.6.faa -dir /mibi/users/jsb562/MAGpy/pfam
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

found less than 4.0 kbp in common. => exiting
[Mon Nov 18 12:52:30 2019]
Finished job 116.
174 of 373 steps (47%) done
found less than 4.0 kbp in common. => exiting
[Mon Nov 18 12:52:32 2019]
Finished job 100.
[Mon Nov 18 12:53:07 2019]
Finished job 118.
183 of 373 steps (49%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mibi/users/jsb562/MAGpy/.snakemake/log/2019-11-18T123925.474123.snakemake.log**

Any suggestions?

**Comment by mw55309** [comment]
Hi

is "active_site.dat" in "/mibi/users/jsb562/MAGpy/pfam ??

Cheers
Mick

**Comment by shashankx** [comment]
Yeah, got it.. thank you
