### ISSUE TITLE
phylophlan no longer available

### ISSUE THREAD

**Issue by amojarro** [WatsonLab/MAGpy#21]
Hello,

following the "10 minute install" - hg clone https://bitbucket.org/nsegata/phylophlan does not work as Bitbucket no longer supports Mercurial repositories.

I tried installing phylophlan with conda install phylophlan, pip install phylophlan, and using the GitHub repository but I still receive the following error:

`Activating conda environment: /home/mojarro/MAGpy/.snakemake/conda/3ff88c87
mkdir: cannot create directory ‘./phylophlan/input/205367’: No such file or directory
cp: target './phylophlan/input/205367' is not a directory
/bin/bash: line 3: cd: ./phylophlan: No such file or directory
/bin/bash: line 4: ./phylophlan.py: No such file or directory
mv: cannot stat './output/205367/*.nwk': No such file or directory
mv: cannot stat './output/205367/*.xml': No such file or directory
/bin/bash: line 8: ./phylophlan.py: No such file or directory
mv: cannot stat './output/205367/*.nwk': No such file or directory
mv: cannot stat './output/205367/*.txt': No such file or directory
Waiting at most 5 seconds for missing files.
MissingOutputException in line 109 of /home/mojarro/MAGpy/MAGpy:
Job completed successfully, but some output files are missing. Missing files after 5 seconds:
tree/MAGpy/MAGpy.tree.nwk
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
  File "/home/mojarro/Documents/MiniConda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 544, in handle_job_success
  File "/home/mojarro/Documents/MiniConda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 231, in handle_job_success
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/mojarro/MAGpy/.snakemake/log/2020-08-20T114738.178383.snakemake.log
`

Any suggestions?

**Comment by mw55309** [comment]
If you have PhyloPhlAn installed using conda, then you need to edit the config file to tell MAGpy where it's installed

See https://github.com/WatsonLab/MAGpy/blob/master/config.json

You will see by default the PhyloPhlAn directory is "./phylophlan" which is where all your errors are coming from

I basically need to update MAGpy to use the conda version, but finding time is the issue....

**Comment by amojarro** [comment]
So after some trial and error I figured out that the environment called by MAGpy for PhyloPhlAn is Python 2.7

`Activating conda environment: /home/mojarro/Documents/MAGs/MAGpy/.snakemake/conda/71dbf22f`

I had initially downloaded PhyloPhlAn 3.0 but then found the PhyloPhlAn 1.0 release and got it to work.
