### ISSUE TITLE
Error during "Looking for PhyloPhlAn proteins in input faa files"

### ISSUE THREAD

**Issue by aparadaLP** [WatsonLab/MAGpy#23]
Hello,
I was running the pipeline, using the command

`(magpy_install) aparada@kuat:~/MAGpy3$ snakemake --use-conda -s MAGpy --jobs 20`

but got the following error message. 

```
Activating conda environment: /media/acclomator/aparada/MAGpy3/.snakemake/conda/30119d31
Looking for PhyloPhlAn proteins in input faa files
Starting data/73535/IMG_2524023116.b6o...
Starting data/73535/IMG_2634166733.b6o...
Starting data/73535/Bin_14_10-contigsRN.b6o...
Starting data/73535/IMG_2634166754.b6o...
Starting data/73535/IMG_2731639251.b6o...
Starting data/73535/CP003842.b6o...
Starting data/73535/Bin_14_19-contigsRN.b6o...
Starting data/73535/IMG_2663763570.b6o...
Starting data/73535/IMG_2731639231.b6o...
Starting data/73535/IMG_2524023110.b6o...
Starting data/73535/CP011070.b6o...
Starting data/73535/IMG_2731639250.b6o...
Starting data/73535/CP007026.b6o...
Starting data/73535/IMG_2524023097.b6o...
Starting data/73535/IMG_2524023101.b6o...
Starting data/73535/IMG_2740891960.b6o...


Invalid command line
Unknown option wdb



Invalid command line
Unknown option wdb

Starting data/73535/IMG_2657245302.b6o...


Invalid command line
Unknown option wdb

```

This combination of "Strating data/....." followed by "Invalid command line Unknown option wdb" goes on until the pipeline exits with the following message.

```

All usearch runs performed!
Traceback (most recent call last):
  File "./phylophlan.py", line 792, in <module>
    faa2ppafaa( inps, pars['nproc'], projn )
  File "./phylophlan.py", line 291, in faa2ppafaa
    for l in open(dat_fol+i+".b6o").readlines()):
IOError: [Errno 2] No such file or directory: 'data/73535/IMG_2524023116.b6o'
mv: cannot stat './output/73535/*.nwk': No such file or directory
mv: cannot stat './output/73535/*.txt': No such file or directory
Waiting at most 5 seconds for missing files.
MissingOutputException in line 109 of /media/acclomator/aparada/MAGpy3/MAGpy:
Missing files after 5 seconds:
tree/MAGpy/MAGpy.tree.nwk
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /media/acclomator/aparada/MAGpy3/.snakemake/log/2020-08-24T150512.835624.snakemake.log

```

Any suggestions on how I can correct this problem?
I've also attached the log file.
[2020-08-24T150512.835624.snakemake.log](https://github.com/WatsonLab/MAGpy/files/5124931/2020-08-24T150512.835624.snakemake.log)

Thanks in advance!
Alma

**Comment by mw55309** [comment]
Hello!

Looks like the wrong version of usearch, see

https://groups.google.com/g/phylophlan-users/c/vAbWtWFwu0s?pli=1

PhyloPhlAn requires an old version, this should be documented in the ten minute install :)

Let me know if that helps

Mick

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by aparadaLP** [comment]
Hmmm, I am seeing the below when I check what usearch version is in my path, which I believe is the version suggested in the 10 minute install.
```
(magpy_install) aparada@kuat:~/MAGpy3$ usearch --version
usearch v5.2.32
```

**Comment by mw55309** [comment]
Do you have any other versions of usearch installed?

I just don't know how PhyloPhlAn runs usearch, and in which shell and under which environment. It's possible it is picking up a different version of usearch on your system...

**Comment by aparadaLP** [comment]
Hello,
The system I was running on it does have other versions of usearch (a shared server). However, I also tried running it on the university cluster, where no other version of usearch should be interfering with the one in my path, but I'm still getting the same error. One thing that came to mind is, does MAGpy depend on phylophlan v1 or should it be able to use the newer v3? Version 3 is what is installed by conda or through github, since it is no longer available through mercurial.

**Comment by mw55309** [comment]
Hello

MAGpy does indeed rely on PhyloPhlAn 2, and won’t work with PhyloPhlAn 3.

PhyloPhlAn 3 is an almost complete re-write and I would go as far as to say it is a completely different piece of software. We are working at integrating PhyloPhlAn 3 but it will take some time….

Mick

**Comment by mw55309** [comment]
Hey

There is a new release today that fixes a lot of sourmash and phylophlan bugs

Please test it!

Cheers
Mick
