### ISSUE TITLE
install phylophlan

### ISSUE THREAD

**Issue by chen318liang** [WatsonLab/MAGpy#24]
The web of https://bitbucket.org/nsegata/phylophlan is seems not available now? Is there other ways to get phylophlan2?

**Comment by dsarov** [comment]
I'm hitting the same error. I've tried installing with conda (conda install -c bioconda phylophlan) but the python version is incompatible. Inclusion in the initial install of the environment (i.e. in the yaml file), might fix this issue?

**Comment by mw55309** [comment]
Hi @dsarov MAGpy works with PhyloPhlAN 2 only - PhyloPhlAN 3 (via conda) is an entirely different piece of software and we haven't figure out how to integrate it yet

To run MAGpy without PhyloPhlAN, remove ```, "tree/MAGpy/MAGpy.tree.nwk"``` from rule all

**Comment by dsarov** [comment]
Thanks! @mw55309

**Comment by mw55309** [comment]
Hey

There is a new release today that fixes a lot of sourmash and phylophlan bugs

Please test it!

Cheers
Mick
