### ISSUE TITLE
Error while running the test 

### ISSUE THREAD

**Issue by mars188** [WatsonLab/MAGpy#25]
Hi,

I installed the MAGpy by following the described steps. But all that, when I tried running the test with the following command:
`snakemake --use-conda -s MAGpy`

I get the following error:

Activating conda environment: /scratch/gencore/ma5877/MAG/MAGpy/.snakemake/conda/f2a7e790
Activating conda environment: /scratch/gencore/ma5877/MAG/MAGpy/.snakemake/conda/0a6540a5
Activating conda environment: /scratch/gencore/ma5877/MAG/MAGpy/.snakemake/conda/3c5b4375
[Tue Nov 17 17:15:54 2020]
Error in rule sourmash_sig:
    jobid: 3
    output: sourmash/ecoli.sig
    conda-env: /scratch/gencore/ma5877/MAG/MAGpy/.snakemake/conda/0a6540a5
    shell:
        sourmash compute --scaled 1000 -k 31 -o sourmash/ecoli.sig mags/ecoli.fa
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Tue Nov 17 17:15:54 2020]
Error in rule checkm:
    jobid: 11
    output: checkm.txt
    conda-env: /scratch/gencore/ma5877/MAG/MAGpy/.snakemake/conda/f2a7e790
    shell:

                checkm_db=/scratch/gencore/ma5877/MAG/checkm_data
                echo ${checkm_db} | checkm data setRoot ${checkm_db}
                checkm lineage_wf -f checkm.txt --reduced_tree -t 16 -x fa mags ./checkm

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Tue Nov 17 17:17:25 2020]
Finished job 8.
1 of 13 steps (8%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

Please help me to fix this issue. Thanks

**Comment by mars188** [comment]
Here is the complete log:

Building DAG of jobs...
Creating conda environment envs/prodigal.yaml...
Downloading and installing remote packages.
Environment for envs/prodigal.yaml created (location: .snakemake/conda/3c5b4375)
Creating conda environment envs/bioperl.yaml...
Downloading and installing remote packages.
Environment for envs/bioperl.yaml created (location: .snakemake/conda/0003c3c9)
Creating conda environment envs/pfam_scan.yaml...
Downloading and installing remote packages.
Environment for envs/pfam_scan.yaml created (location: .snakemake/conda/248d4fef)
Creating conda environment envs/checkm.yaml...
Downloading and installing remote packages.
Environment for envs/checkm.yaml created (location: .snakemake/conda/f2a7e790)
Creating conda environment envs/ete3.yaml...
Downloading and installing remote packages.
Environment for envs/ete3.yaml created (location: .snakemake/conda/6e4bf5f9)
Creating conda environment envs/diamond.yaml...
Downloading and installing remote packages.
Environment for envs/diamond.yaml created (location: .snakemake/conda/67f26a19)
Creating conda environment envs/basic2.yaml...
Downloading and installing remote packages.
Environment for envs/basic2.yaml created (location: .snakemake/conda/4d1ca557)
Creating conda environment envs/sourmash.yaml...
Downloading and installing remote packages.
Environment for envs/sourmash.yaml created (location: .snakemake/conda/0a6540a5)
Using shell: /bin/bash
Provided cores: 28
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       checkm
        1       checkm_plus
        1       diamond
        1       diamond_bin_summary
        1       diamond_bin_summary_plus
        1       diamond_report
        1       pfam_scan
        1       phylophlan_link
        1       prodigal
        1       sourmash_gather
        1       sourmash_report
        1       sourmash_sig
        13

[Tue Nov 17 17:15:52 2020]
rule prodigal:
    input: mags/ecoli.fa
    output: proteins/ecoli.faa, proteins/ecoli_prodigal.gff
    jobid: 8
    wildcards: id=ecoli


[Tue Nov 17 17:15:52 2020]
rule checkm:
    input: mags
    output: checkm.txt
    jobid: 11
    threads: 16


[Tue Nov 17 17:15:52 2020]
rule sourmash_sig:
    input: mags/ecoli.fa
    output: sourmash/ecoli.sig
    jobid: 3
    wildcards: id=ecoli

Activating conda environment: /scratch/gencore/ma5877/MAG/MAGpy/.snakemake/conda/f2a7e790
Activating conda environment: /scratch/gencore/ma5877/MAG/MAGpy/.snakemake/conda/0a6540a5
Activating conda environment: /scratch/gencore/ma5877/MAG/MAGpy/.snakemake/conda/3c5b4375
/bin/bash: sourmash: command not found
/bin/bash: line 1: checkm: command not found
[Tue Nov 17 17:15:54 2020]
Error in rule sourmash_sig:
/bin/bash: line 2: checkm: command not found
    jobid: 3
    output: sourmash/ecoli.sig
    conda-env: /scratch/gencore/ma5877/MAG/MAGpy/.snakemake/conda/0a6540a5
    shell:
        sourmash compute --scaled 1000 -k 31 -o sourmash/ecoli.sig mags/ecoli.fa
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Tue Nov 17 17:15:54 2020]
Error in rule checkm:
    jobid: 11
    output: checkm.txt
    conda-env: /scratch/gencore/ma5877/MAG/MAGpy/.snakemake/conda/f2a7e790
    shell:

                checkm_db=/scratch/gencore/ma5877/MAG/checkm_data
                echo ${checkm_db} | checkm data setRoot ${checkm_db}
                checkm lineage_wf -f checkm.txt --reduced_tree -t 16 -x fa mags ./checkm

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Tue Nov 17 17:17:25 2020]
Finished job 8.
1 of 13 steps (8%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /scratch/gencore/ma5877/MAG/MAGpy/.snakemake/log/2020-11-17T170653.385976.snakemake.log

**Comment by mw55309** [comment]
Hey

There is a new release today that fixes a lot of sourmash and phylophlan bugs

Please test it!

Cheers
Mick
