### ISSUE TITLE
usearch error

### ISSUE THREAD

**Issue by mars188** [WatsonLab/MAGpy#26]
I am at the first step of MAGpy installation. I downloaded the usearch file and then tried to change mode to make it executable but I get the following error: 
`chmod: changing permissions of ‘usearch’: Operation not permitted`

How can we fix that? Also, can I complete the analysis without usearch installed?

Thanks,

**Comment by mw55309** [comment]
I think you need to contact your local sys/admin - chmod of a file you own should be simple!

**Comment by mw55309** [comment]
Hey

There is a new release today that fixes a lot of sourmash and phylophlan bugs

Please test it!

Cheers
Mick
