### ISSUE TITLE
Question about databases

### ISSUE THREAD

**Issue by smb20200615** [WatsonLab/MAGpy#27]
Hello,

I have been testing out your tool with my bacterial MAGs. Most of the diamond hits get assigned to archaea. I used the 10 minute install guideline for setting up the databases. Do you have any idea on why this could be happening? I am new to your work and don't know where to start with the troubleshooting.

Thank you and happy new year!

**Comment by mw55309** [comment]
Are you using uniprot swiss-prot or uniprot TREMBL?

Could you post an example of a FASTA sequence?

**Comment by mw55309** [comment]
Hey

There is a new release today that fixes a lot of sourmash and phylophlan bugs

Please test it!

Cheers
Mick
