### ISSUE TITLE
phylophlan 3

### ISSUE THREAD

**Issue by geo80** [WatsonLab/MAGpy#28]
Hi,

I'm trying to run MAGpy, but I suspect that the setup regarding phylophlan is based on version 2, which is currently unavailable, rather than the newest version 3.
Any idea how to modify the file MAGpy to run the new version?

Thanks

**Comment by mw55309** [comment]
It would be great to integrate PhyloPhlAn 3 into MAGpy but A LOT has changed, and finding time to do this will be tough.

To run MAGpy without PhyloPhlAn 2 (which is hard to come by), change the file ```MAGpy```:

```sh
rule all:
	 input: "sourmash_report.csv", "diamond_bin_report_plus.tsv", expand("pfam/{sample}.pfam", sample=IDS), expand("sourmash/{sample}.sm", sample=IDS), expand("diamond_report/bin.{sample}.tsv", sample=IDS), "checkm_plus.txt", "tree/MAGpy/MAGpy.tree.nwk"
```

Becomes

```sh
rule all:
	 input: "sourmash_report.csv", "diamond_bin_report_plus.tsv", expand("pfam/{sample}.pfam", sample=IDS), expand("sourmash/{sample}.sm", sample=IDS), expand("diamond_report/bin.{sample}.tsv", sample=IDS), "checkm_plus.txt"
```

**Comment by geo80** [comment]
> It would be great to integrate PhyloPhlAn 3 into MAGpy but A LOT has changed, and finding time to do this will be tough.

I realized that! I was trying to confuse it and get some sort of similar results, but it looks like a totally different program.

Thanks. I will change the file as you suggest. Thanks.

Maybe you can update the manual that phylophlan does not work anymore...

Cheers,
