### ISSUE TITLE
Running a subset of jobs?

### ISSUE THREAD

**Issue by adityabandla** [WatsonLab/MAGpy#3]
Can a subset of jobs alone be run instead of all?

**Comment by mw55309** [comment]
It depends what you mean.

To run everything on a subset of mags, just put fewer .fa files into the mags directory.

To run a different subset of the pipeline would require a bit of altering of the rule all, but it shouldn't be too hard....

**Comment by adityabandla** [comment]
Hi Mick

Apologies for the vague phrasing. I meant running a subset of the pipeline. I managed to figure out how to alter the snakemake pipeline

On another note, I think there is a bug in the rule definition for the phylophlan step. Once the output from Phylophlan is copied into the tree folder, the newick tree file still has the name of the process ID and not MAGpy.tree.nwk. So this throws a missing output file error

**Comment by mw55309** [comment]
Thanks, will look into it :)
