### ISSUE TITLE
Seems promising but??

### ISSUE THREAD

**Issue by pythseq** [WatsonLab/MAGpy#4]
The pipeline seems promising since it uses several tools, is it possible to get examples or tutorial to show most relevant of its functionalities.

Thanks

**Comment by mw55309** [comment]
Currently working on tests and trying to cope with the mega slow-down of conda, will get to a tutorial after that

**Comment by pythseq** [comment]
thanks waiting for ...

**Comment by mw55309** [comment]
Tests are up
