### ISSUE TITLE
WARNING: the sourmash compute command is DEPRECATED as of 4.0 and  will be removed in 5.0.

### ISSUE THREAD

**Issue by LiuYajing0914** [WatsonLab/MAGpy#40]
Hi,Dear Sir！
    I had some questions when I used this pipeline.The Sourmash's Options seem to something wrong!
    First question,the sourmash is useful,but the "test_results.txt" is print 
"Sourmash ran with some errors: 
== This is sourmash version 4.1.1. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. =="
    why?
   Next question,when I used  "snakemake -rp -s MAGpy --use-conda all  --cores 16"，the log file was found this：
“** WARNING: the sourmash compute command is DEPRECATED as of 4.0 and
  ** will be removed in 5.0. Please see the 'sourmash sketch' command instead.”
   I don't know my results are correct or not?
Thanks!

**Comment by mw55309** [comment]
I think this is OK, we can continue to use sourmash 4 for the time being :)

**Comment by LiuYajing0914** [comment]
Ok,i got it,thank you!😁
