### ISSUE TITLE
MAGpy/envs/install.yaml is missing!!

### ISSUE THREAD

**Issue by yoobios** [WatsonLab/MAGpy#6]
According to install.md (https://github.com/WatsonLab/MAGpy/blob/master/install.md), in step 5 create the main MAGpy environment: 
conda env create -f MAGpy/envs/install.yaml

But the install.yaml is missing. So I got this error warning.
SpecNotFound: Can't process without a name.

Thank you

**Comment by yoobios** [comment]
Can I just install other .yaml files (eg. sourmash.yaml, ete3.yaml) directly to any conda environment I already have?

**Comment by mw55309** [comment]
Apologies, install.yaml had been committed but not pushed - it is there now.

You can't install everything into a single env as some are python 3 and some are python 2

We used to have single, larger envs but they were taking 7 hours for conda to resolve - not good.
